version: "3.9"

services:
  database:
    image: library/postgres:14.0-alpine
    container_name: chat_code_sample_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-0000}
    ports:
    - 5432:5432
    networks:
      db:
        ipv4_address: 172.16.238.10
  redis:
    image: library/redis:6.2-alpine
    container_name: cache
    ports:
      - 6379:6379
    networks:
      - backend
  api:
    build: .
    container_name: chat_code_sample_api
    ports:
      - 3000:3000
    depends_on:
      - database
      - redis
    networks:
      - backend
    environment:
      - REDIS_URL=redis
networks:
  backend:
    driver: bridge
  db:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1